name: Build and test

on: 
  workflow_call:
    inputs:
      name:
        description: 'The name of the binary'
        required: true
        type: string

jobs: 
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read  # Minimal required permissions

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{github.workspace}}/libtui/go.mod
    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ar
        run: |
          pacman -S mingw-w64-x86_64-binutils
          x86_64-w64-mingw32-ar --version
        if: matrix.os == 'windows-latest'

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: '3.25.1'
          
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.14.0



      - name: Verify Go installation
        run: go version

      - name: Verify CMake installation
        run: cmake --version


      - name: Build project and test
        run: 
          python3 ${{ github.workspace }}/.github/builder.py -o ./dist -t 

      - name: Rename binary
        run: 
          python3 .github/rename.py ./dist
        env: 
          INF: ${{matrix.os}}

      - name: Upload Binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.name}}-${{ matrix.os }}.bin
          path: dist/