name: Build and test

on: 
  workflow_call:
    inputs:
      name:
        description: 'The name of the binary'
        required: true
        type: string

jobs: 
  build:
    name: Build binaries
    runs-on: ${{ matrix.config.build-os }}

    permissions:
      contents: read  # Minimal required permissions

    strategy:
      fail-fast: false
      matrix:
        config:
          - { build-os: "ubuntu-latest", build-slot: "github-actions-linux", inf: "linux"}
          - { build-os: "ubuntu-latest", build-slot: "github-actions-windows", inf: "win"}
          - { build-os: "macos-latest", build-slot: "github-actions-darwin", inf: "darwin"}    

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{github.workspace}}/libtui/go.mod
    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: '3.25.1'

      - name: Setup Google test
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.14.0
      - name: Install MinGW
        if: matrix.config.build-slot == 'github-actions-windows'
        run: mingw-w64-tools

      - name: Verify Go installation
        run: go version

      - name: Verify CMake installation
        run: cmake --version

      - name: Build project and test
        run: 
          python3 ${{ github.workspace }}/.github/builder.py -o ./dist -s ${{matrix.config.build-slot}} --test

      - name: Rename binary
        run: 
          python3 .github/rename.py ./dist
        env: 
          INF: ${{matrix.config.inf}}
          NAME: ${{inputs.name}}

      - name: Upload Binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.name}}-${{ matrix.config.inf }}.bin
          path: dist/