name: Continuous Integration (CI)

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/'
  push:
    branches:
        - master
        - dev
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Build Project
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    with: 
      name: virtualshelf