name: Release

on:
  workflow_call:
    inputs:
      dry-run:
        type: boolean
        default: true
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install semantic-release dependencies
        run: |
          npm install --save-dev \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/exec \
            @semantic-release/gitlab \
            @semantic-release/npm \
            @semantic-release/release-notes-generator \
            conventional-changelog-conventionalcommits

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: dist/
        if: ${{ inputs.dry-run != 'true' }}
        
      - name: Move Binary files to root of dist
        run: |
          find dist -mindepth 2 -type f -exec mv -t dist {} +
          find dist -mindepth 1 -type d -exec rm -r {} +
        if: ${{ inputs.dry-run != 'true' }}

      - name: Run semantic-release
        run: |
          if [ "${{ inputs.dry-run }}" == true ]; then
            echo "Running in dry-run mode"
            npx semantic-release --config .github/.releaserc.js --dry-run
          else
            echo "Running semantic-release normally"
            npx semantic-release --config .github/.releaserc.js
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
