name: Test

on: 
  workflow_call:

jobs: 
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read  # Minimal required permissions

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]  # Add support for multiple architectures

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{github.workspace}}/libtui/go.mod
    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: '3.25.1'

        
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.14.0
        
      - name: Install sqlite for windows
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install sqlite3:x64-windows
          echo "CMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
        if: ${{ matrix.os == 'windows-latest'}}

      - name: Verify Go installation
        run: go version

      - name: Verify CMake installation
        run: cmake --version

      - run: python3 -m pip install gitpython

      - name: Build project
        run: 
          python3 ${{ github.workspace }}/.github/builder.py -o ./dist -t Release --test