name: Test

on: 
  workflow_call:

jobs: 
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read  # Minimal required permissions

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # arch: [amd64, arm64]  # Add support for multiple architectures

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{github.workspace}}/libtui/go.mod
    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        if: matrix.os != 'windows-latest'
        with:
          version: '3.25.1'

        
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: Bacondish2023/setup-googletest@v1
        if: matrix.os != 'windows-latest'
        with:
          tag: v1.14.0
        

      - 
        name: Setup Docker
        uses: docker/setup-docker-action@v4
      
      
      - name: Build go project
        run: cd libtui && go build -buildmode=c-archive -o ../libtui.lib .
        if: matrix.os == 'windows-latest'

      - name: Build Dockerized project
        run: |
          docker build -t virtualshelf .
          docker run --rm -v $(pwd):/output virtualshelf
        if: matrix.os == 'windows-latest'

      

      - run: python3 -m pip install gitpython

      - name: Build project
        run: 
          python3 ${{ github.workspace }}/.github/builder.py -o ./dist -t Release --test
        if: matrix.os != 'windows-latest'